const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const toast=$('#toast');const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),del:k=>localStorage.removeItem(k)};let user=store.get('stylo-user',null);let prefs=store.get('stylo-prefs',{name:'Alex Rivera',email:'alex@example.com',size:'M / 32',shoe:'10.5',budget:'$100-$250 per item',colors:'Black, taupe, violet',done:false});
function note(t){toast.textContent=t;toast.classList.add('show');clearTimeout(note.t);note.t=setTimeout(()=>toast.classList.remove('show'),2400)}
function route(name){if(name==='outfits')name='closet';$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.route===name));history.replaceState(null,'','#'+name);scrollTo({top:0,behavior:'smooth'})}
$$('[data-route]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();route(el.dataset.route)}));if(location.hash&&$(location.hash.replace('outfits','closet')))route(location.hash.slice(1));
$('#themeToggle').onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('stylo-theme',n);note(`${n} mode enabled`)};document.documentElement.dataset.theme=localStorage.getItem('stylo-theme')||'dark';
function fillForms(){['Name','Email','Size','Shoe','Budget','Colors'].forEach(x=>{const key=x.toLowerCase();const v=prefs[key]||'';const p=$('#pref'+x),f=$('#profile'+x);if(p)p.value=v;if(f)f.value=v});updateProfile()}
function updateProfile(){const name=user?.name||prefs.name||'Guest stylist';const email=user?.email||prefs.email||'Sign in to save your profile';$('#profileNameText').textContent=name;$('#profileEmailText').textContent=user?email:'Sign in to save your profile';$('#avatar').textContent=(name[0]||'S').toUpperCase();$('#openAuth').textContent=user?'Profile':'Sign in';$('#signOut').hidden=!user}
function savePrefs(prefix){prefs={name:$('#'+prefix+'Name').value,email:$('#'+prefix+'Email').value,size:$('#'+prefix+'Size').value,shoe:$('#'+prefix+'Shoe').value,budget:$('#'+prefix+'Budget').value,colors:$('#'+prefix+'Colors').value,done:true};store.set('stylo-prefs',prefs);if(user){user={...user,name:prefs.name,email:prefs.email};store.set('stylo-user',user)}fillForms();note('Preferences saved')}
$('#openPrefs').onclick=()=>{$('#prefsModal').showModal();fillForms()};$('#profileForm').onsubmit=e=>{e.preventDefault();savePrefs('profile')};$('#prefsForm').onsubmit=e=>{e.preventDefault();savePrefs('pref');$('#prefsModal').close();route('profile')};
$('#openAuth').onclick=()=>{user?route('profile'):$('#authModal').showModal()};function signIn(provider){const email=$('#authEmail').value||prefs.email;user={provider,email,name:prefs.name||email.split('@')[0],at:new Date().toISOString()};store.set('stylo-user',user);$('#authModal').close();fillForms();if(!prefs.done){$('#prefsModal').showModal();note(`Signed in with ${provider}. Add your preferences.`)}else{route('profile');note(`Signed in with ${provider}`)}}$('#authForm').onsubmit=e=>{e.preventDefault();signIn('Email')};$('#googleSignIn').onclick=()=>signIn('Google');$('#appleSignIn').onclick=()=>signIn('Apple');$('#forgotPassword').onclick=()=>{$('#resetPanel').hidden=false;$('#resetEmail').value=$('#authEmail').value;note('Password recovery ready')};$('#sendReset').onclick=()=>note(`Reset link sent to ${$('#resetEmail').value||'your email'}`);$('#signOut').onclick=()=>{user=null;store.del('stylo-user');updateProfile();note('Signed out')};
const pieces={blazer:[['Taupe blazer','94% match · wool · business casual'],['Soft blazer','88% match · authorized retailer']],shirt:[['Black fitted tee','91% match · cotton base'],['Ivory knit','86% match · old money']],pants:[['Charcoal pants','89% match · tapered neutral'],['Cream trouser','84% match · relaxed formal']],shoes:[['White low sneaker','93% match · travel-ready'],['Brown loafer','87% match · polished casual']],bag:[['Violet tote','91% match · statement accent'],['City bag','85% match · workday']]};function norm(q){q=q.toLowerCase();if(q.includes('bag')||q.includes('tote'))return'bag';if(q.includes('shoe')||q.includes('sneaker')||q.includes('loafer')||q.includes('boot'))return'shoes';if(q.includes('pant')||q.includes('trouser')||q.includes('jean'))return'pants';if(q.includes('shirt')||q.includes('tee')||q.includes('knit'))return'shirt';return'blazer'}function found(piece,target){$(target).innerHTML=pieces[piece].map(([a,b])=>`<article><b>${a}</b><span>${b}</span></article>`).join('')}function hi(piece,scope=document){$$('.hot',scope).forEach(h=>h.classList.toggle('active',h.dataset.piece===piece))}
$('#pieceSearchButton').onclick=()=>{const p=norm($('#pieceSearchInput').value);hi(p,$('#closet'));found(p,'#detectedPieces');note(`${p} found inside photo`)};$('#resetPhotoSearch').onclick=()=>{$('#pieceSearchInput').value='blazer';hi('blazer',$('#closet'));found('blazer','#detectedPieces')};found('blazer','#detectedPieces');
$('#chooseFiles').onclick=()=>$('#closetUpload').click();$('#closetUpload').onchange=e=>addItems(e.target.files);function addItems(files){[...files].slice(0,6).forEach(f=>{$('#inventoryGrid').insertAdjacentHTML('afterbegin',`<article><i class="piece blazer"></i><b>${f.name.replace(/\.[^.]+$/,'').slice(0,28)}</b><span>AI detected · ready to edit</span></article>`)});if(files.length)note(`${files.length} item${files.length>1?'s':''} added`)}['dragenter','dragover'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.add('drag')}));['dragleave','drop'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.remove('drag')}));$('#dropzone').ondrop=e=>addItems(e.dataTransfer.files);$('#sortCloset').onclick=()=>{$$('#inventoryGrid article').reverse().forEach(c=>$('#inventoryGrid').append(c));note('Closet sorted')};
const looks=[['Balanced business casual',['Taupe blazer','Black tee','Charcoal trouser','White sneaker'],'Balanced neutrals elongate the silhouette while the sneaker keeps the look relaxed.'],['Old money dinner edit',['Navy blazer','Ivory knit','Cream trouser','Brown loafer'],'Warm ivory and navy create a refined contrast.'],['Rain-smart city travel',['Black shell','Merino tee','Utility pant','Waterproof sneaker'],'Weather-safe materials keep the look practical and clean.']];let li=0;$('#generateOutfit').onclick=()=>{li=(li+1)%looks.length;const l=looks[li];$('#outfitTitle').textContent=l[0];$$('#outfitPieces b').forEach((b,i)=>b.textContent=l[1][i]);$('#outfitReason').textContent=l[2];note('New outfit generated')};$('#replaceShoes').onclick=()=>{const b=$$('#outfitPieces b')[3];b.textContent=b.textContent.includes('sneaker')?'Brown loafer':'White sneaker';note('Shoes replaced')};
document.addEventListener('click',e=>{if(e.target.closest('.save')){const b=e.target.closest('.save');b.textContent=b.textContent.includes('♥')?'♡ Save':'♥ Saved';note('Saved state updated')}if(e.target.closest('.stars button')){const wrap=e.target.closest('.stars');const buttons=$$('.stars button',wrap);const n=buttons.indexOf(e.target)+1;buttons.forEach((b,i)=>b.textContent=i<n?'★':'☆');$('span',wrap).textContent=`${n}.0`;note(`Rated ${n} out of 5`)}});
document.addEventListener('submit',e=>{if(!e.target.classList.contains('comment'))return;e.preventDefault();const input=$('input',e.target);if(!input.value.trim())return;e.target.previousElementSibling.insertAdjacentHTML('beforeend',`<article><b>${user?.name?.split(' ')[0]||'You'}</b><span>${input.value}</span></article>`);input.value='';note('Comment posted')});
$('#publishOutfit').onclick=()=>{const name=user?.name||prefs.name||'Stylo user';const caption=$('#communityCaption').value||'New Stylo community outfit';$('#communityFeed').insertAdjacentHTML('afterbegin',`<article class="post"><div class="photo"><button class="hot bag active" data-piece="bag">Bag</button><div class="model"><i></i><b></b><em></em><strong></strong></div></div><div><div class="author"><span>${name[0]}</span><b>${name}</b></div><p>${caption}</p><div class="stars"><button>☆</button><button>☆</button><button>☆</button><button>☆</button><button>☆</button><span>New</span></div><div class="comments"></div><form class="comment"><input placeholder="Leave a comment"/><button class="icon">↑</button></form></div></article>`);$('#communityCaption').value='';note('Outfit posted')};$('#communityPieceButton').onclick=()=>{const p=norm($('#communityPieceSearch').value);hi(p,$('#community'));$('#communitySearchResult').innerHTML=`<b>${pieces[p][0][0]} found</b><span>${pieces[p][0][1]} · community photo search</span>`;note(`${p} highlighted in community`)};
$('#runDiscover').onclick=()=>note(`Searching for "${$('#discoverSearch').value}"`);$('#animateTryon').onclick=()=>note('Try-on render refreshed');fillForms();
