const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];const toast=$('#toast');const store={get:(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}},set:(k,v)=>localStorage.setItem(k,JSON.stringify(v)),del:k=>localStorage.removeItem(k)};let user=store.get('stylo-user',null);let prefs=store.get('stylo-prefs',{name:'Alex Rivera',email:'alex@example.com',size:'M / 32',shoe:'10.5',budget:'$100-$250 per item',colors:'Black, taupe, violet',done:false});
function note(t){toast.textContent=t;toast.classList.add('show');clearTimeout(note.t);note.t=setTimeout(()=>toast.classList.remove('show'),2400)}
function route(name){if(name==='outfits')name='closet';$$('.view').forEach(v=>v.classList.toggle('active',v.id===name));$$('.tab').forEach(b=>b.classList.toggle('active',b.dataset.route===name));history.replaceState(null,'','#'+name);scrollTo({top:0,behavior:'smooth'})}
$$('[data-route]').forEach(el=>el.addEventListener('click',e=>{e.preventDefault();route(el.dataset.route)}));if(location.hash&&$(location.hash.replace('outfits','closet')))route(location.hash.slice(1));
$('#themeToggle').onclick=()=>{const n=document.documentElement.dataset.theme==='dark'?'light':'dark';document.documentElement.dataset.theme=n;localStorage.setItem('stylo-theme',n);note(`${n} mode enabled`)};document.documentElement.dataset.theme=localStorage.getItem('stylo-theme')||'dark';
function fillForms(){['Name','Email','Size','Shoe','Budget','Colors'].forEach(x=>{const key=x.toLowerCase();const v=prefs[key]||'';const p=$('#pref'+x),f=$('#profile'+x);if(p)p.value=v;if(f)f.value=v});updateProfile()}
function updateProfile(){const name=user?.name||prefs.name||'Guest stylist';const email=user?.email||prefs.email||'Sign in to save your profile';$('#profileNameText').textContent=name;$('#profileEmailText').textContent=user?email:'Sign in to save your profile';$('#avatar').textContent=(name[0]||'S').toUpperCase();$('#openAuth').textContent=user?'Profile':'Sign in';$('#signOut').hidden=!user}
function savePrefs(prefix){prefs={name:$('#'+prefix+'Name').value,email:$('#'+prefix+'Email').value,size:$('#'+prefix+'Size').value,shoe:$('#'+prefix+'Shoe').value,budget:$('#'+prefix+'Budget').value,colors:$('#'+prefix+'Colors').value,done:true};store.set('stylo-prefs',prefs);if(user){user={...user,name:prefs.name,email:prefs.email};store.set('stylo-user',user)}fillForms();note('Preferences saved')}
$('#openPrefs').onclick=()=>{$('#prefsModal').showModal();fillForms()};$('#profileForm').onsubmit=e=>{e.preventDefault();savePrefs('profile')};$('#prefsForm').onsubmit=e=>{e.preventDefault();savePrefs('pref');$('#prefsModal').close();route('profile')};
$('#openAuth').onclick=()=>{user?route('profile'):$('#authModal').showModal()};function signIn(provider){const email=$('#authEmail').value||prefs.email;user={provider,email,name:prefs.name||email.split('@')[0],at:new Date().toISOString()};store.set('stylo-user',user);$('#authModal').close();fillForms();if(!prefs.done){$('#prefsModal').showModal();note(`Signed in with ${provider}. Add your preferences.`)}else{route('profile');note(`Signed in with ${provider}`)}}$('#authForm').onsubmit=e=>{e.preventDefault();signIn('Email')};$('#googleSignIn').onclick=()=>signIn('Google');$('#appleSignIn').onclick=()=>signIn('Apple');$('#forgotPassword').onclick=()=>{$('#resetPanel').hidden=false;$('#resetEmail').value=$('#authEmail').value;note('Password recovery ready')};$('#sendReset').onclick=()=>note(`Reset link sent to ${$('#resetEmail').value||'your email'}`);$('#signOut').onclick=()=>{user=null;store.del('stylo-user');updateProfile();note('Signed out')};
const pieces={blazer:[['Taupe blazer','94% match · wool · business casual'],['Soft blazer','88% match · authorized retailer']],shirt:[['Black fitted tee','91% match · cotton base'],['Ivory knit','86% match · old money']],pants:[['Charcoal pants','89% match · tapered neutral'],['Cream trouser','84% match · relaxed formal']],shoes:[['White low sneaker','93% match · travel-ready'],['Brown loafer','87% match · polished casual']],bag:[['Violet tote','91% match · statement accent'],['City bag','85% match · workday']]};function norm(q){q=q.toLowerCase();if(q.includes('bag')||q.includes('tote'))return'bag';if(q.includes('shoe')||q.includes('sneaker')||q.includes('loafer')||q.includes('boot'))return'shoes';if(q.includes('pant')||q.includes('trouser')||q.includes('jean'))return'pants';if(q.includes('shirt')||q.includes('tee')||q.includes('knit'))return'shirt';return'blazer'}function found(piece,target){$(target).innerHTML=pieces[piece].map(([a,b])=>`<article><b>${a}</b><span>${b}</span></article>`).join('')}function hi(piece,scope=document){$$('.hot',scope).forEach(h=>h.classList.toggle('active',h.dataset.piece===piece))}
$('#pieceSearchButton').onclick=()=>{const p=norm($('#pieceSearchInput').value);hi(p,$('#closet'));found(p,'#detectedPieces');note(`${p} found inside photo`)};$('#resetPhotoSearch').onclick=()=>{$('#pieceSearchInput').value='blazer';hi('blazer',$('#closet'));found('blazer','#detectedPieces')};found('blazer','#detectedPieces');
$('#chooseFiles').onclick=()=>$('#closetUpload').click();$('#closetUpload').onchange=e=>addItems(e.target.files);function addItems(files){[...files].slice(0,6).forEach(f=>{$('#inventoryGrid').insertAdjacentHTML('afterbegin',`<article><i class="piece blazer"></i><b>${f.name.replace(/\.[^.]+$/,'').slice(0,28)}</b><span>AI detected · ready to edit</span></article>`)});if(files.length)note(`${files.length} item${files.length>1?'s':''} added`)}['dragenter','dragover'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.add('drag')}));['dragleave','drop'].forEach(n=>$('#dropzone').addEventListener(n,e=>{e.preventDefault();$('#dropzone').classList.remove('drag')}));$('#dropzone').ondrop=e=>addItems(e.dataTransfer.files);$('#sortCloset').onclick=()=>{$$('#inventoryGrid article').reverse().forEach(c=>$('#inventoryGrid').append(c));note('Closet sorted')};
const looks=[['Balanced business casual',['Taupe blazer','Black tee','Charcoal trouser','White sneaker'],'Balanced neutrals elongate the silhouette while the sneaker keeps the look relaxed.'],['Old money dinner edit',['Navy blazer','Ivory knit','Cream trouser','Brown loafer'],'Warm ivory and navy create a refined contrast.'],['Rain-smart city travel',['Black shell','Merino tee','Utility pant','Waterproof sneaker'],'Weather-safe materials keep the look practical and clean.']];let li=0;$('#generateOutfit').onclick=()=>{li=(li+1)%looks.length;const l=looks[li];$('#outfitTitle').textContent=l[0];$$('#outfitPieces b').forEach((b,i)=>b.textContent=l[1][i]);$('#outfitReason').textContent=l[2];note('New outfit generated')};$('#replaceShoes').onclick=()=>{const b=$$('#outfitPieces b')[3];b.textContent=b.textContent.includes('sneaker')?'Brown loafer':'White sneaker';note('Shoes replaced')};
document.addEventListener('click',e=>{if(e.target.closest('.save')){const b=e.target.closest('.save');b.textContent=b.textContent.includes('♥')?'♡ Save':'♥ Saved';note('Saved state updated')}if(e.target.closest('.stars button')){const wrap=e.target.closest('.stars');const buttons=$$('.stars button',wrap);const n=buttons.indexOf(e.target)+1;buttons.forEach((b,i)=>b.textContent=i<n?'★':'☆');$('span',wrap).textContent=`${n}.0`;note(`Rated ${n} out of 5`)}});
document.addEventListener('submit',e=>{if(!e.target.classList.contains('comment'))return;e.preventDefault();const input=$('input',e.target);if(!input.value.trim())return;e.target.previousElementSibling.insertAdjacentHTML('beforeend',`<article><b>${user?.name?.split(' ')[0]||'You'}</b><span>${input.value}</span></article>`);input.value='';note('Comment posted')});
$('#publishOutfit').onclick=()=>{const name=user?.name||prefs.name||'Stylo user';const caption=$('#communityCaption').value||'New Stylo community outfit';$('#communityFeed').insertAdjacentHTML('afterbegin',`<article class="post"><div class="photo"><button class="hot bag active" data-piece="bag">Bag</button><div class="model"><i></i><b></b><em></em><strong></strong></div></div><div><div class="author"><span>${name[0]}</span><b>${name}</b></div><p>${caption}</p><div class="stars"><button>☆</button><button>☆</button><button>☆</button><button>☆</button><button>☆</button><span>New</span></div><div class="comments"></div><form class="comment"><input placeholder="Leave a comment"/><button class="icon">↑</button></form></div></article>`);$('#communityCaption').value='';note('Outfit posted')};$('#communityPieceButton').onclick=()=>{const p=norm($('#communityPieceSearch').value);hi(p,$('#community'));$('#communitySearchResult').innerHTML=`<b>${pieces[p][0][0]} found</b><span>${pieces[p][0][1]} · community photo search</span>`;note(`${p} highlighted in community`)};
$('#runDiscover').onclick=()=>note(`Searching for "${$('#discoverSearch').value}"`);$('#animateTryon').onclick=()=>note('Try-on render refreshed');fillForms();
(function improveHome(){
  if(document.getElementById('productProof')) return;
  const style=document.createElement('style');
  style.textContent=`
    .hero-badges,.proof,.workflow,.readiness{display:grid;gap:1rem}.hero-badges{grid-template-columns:repeat(3,max-content);margin:1rem 0}.hero-badges span{border:1px solid var(--line);border-radius:999px;background:rgba(255,255,255,.06);color:var(--muted);font-size:.76rem;font-weight:900;padding:.42rem .7rem}.proof{grid-template-columns:repeat(3,1fr);margin-top:1rem}.proof article,.workflow article,.readiness article{border:1px solid var(--line);border-radius:var(--r);background:var(--panel);box-shadow:var(--shadow);backdrop-filter:blur(20px);padding:1rem}.proof b,.workflow b,.readiness b{display:block;margin-bottom:.3rem}.proof span,.workflow p,.readiness span{color:var(--muted)}.product-section{margin-top:1rem}.product-section>.title{max-width:48rem}.workflow{grid-template-columns:repeat(3,1fr)}.workflow article{min-height:14rem}.step{display:inline-flex;margin-bottom:1.8rem;border-radius:999px;background:linear-gradient(135deg,rgba(109,92,255,.24),rgba(255,110,182,.16));color:var(--pink);font-size:.76rem;font-weight:900;padding:.35rem .65rem}.launch{display:grid;grid-template-columns:.9fr 1.1fr;gap:1rem;align-items:start;border:1px solid var(--line);border-radius:var(--r);background:linear-gradient(135deg,rgba(109,92,255,.14),rgba(255,110,182,.08));box-shadow:var(--shadow);padding:1.2rem}.readiness{gap:.75rem}.readiness article{background:var(--strong)}@media(max-width:960px){.hero-badges,.proof,.workflow,.launch{grid-template-columns:1fr}.workflow article{min-height:auto}}
  `;
  document.head.append(style);
  const heroText=document.querySelector('#home .hero p:not(.eyebrow)');
  if(heroText){heroText.insertAdjacentHTML('afterend',`<div class="hero-badges"><span>Private closet data</span><span>AI outfit reasoning</span><span>Community style feedback</span></div>`)}
  const home=document.getElementById('home');
  if(home){home.insertAdjacentHTML('beforeend',`
    <section id="productProof" class="proof" aria-label="Stylo proof points"><article><b>App-ready flows</b><span>Sign-in, onboarding, profile, closet upload, visual search, community, and try-on are represented.</span></article><article><b>Consent-first AI</b><span>Private image use, try-on consent, and deletion messaging are visible before sensitive features.</span></article><article><b>Built for expansion</b><span>The interface maps cleanly to future backend APIs, computer vision, shopping data, and mobile apps.</span></article></section>
    <section class="product-section" aria-label="How Stylo works"><div class="title"><p class="eyebrow">How It Works</p><h2>From closet chaos to ready-to-wear decisions.</h2><p>Stylo should feel useful before it feels flashy: capture the wardrobe, understand the user, then explain every recommendation.</p></div><div class="workflow"><article><span class="step">01</span><b>Build your style profile</b><p>Collect fit, budget, color, brand, climate, dress code, and aesthetic preferences during first sign-in.</p></article><article><span class="step">02</span><b>Digitize and search photos</b><p>Upload closet images, detect pieces, and search inside outfit photos for blazers, shirts, pants, shoes, and bags.</p></article><article><span class="step">03</span><b>Generate looks with reasons</b><p>Get outfit options with match scores, swap controls, try-on previews, and clear styling explanations.</p></article></div></section>
    <section class="product-section launch" aria-label="Launch readiness"><div><p class="eyebrow">Launch Readiness</p><h2>What feels strong, and what should become real next.</h2><p>This site now communicates the product vision well. The next leap is replacing demo data with real accounts, secure image storage, computer vision, and a mobile app build for App Store review.</p></div><div class="readiness"><article><b>Strong now</b><span>Branding, navigation, core feature story, interactive demos, GitHub Pages deployment.</span></article><article><b>Needs backend</b><span>Real authentication, persistent closet items, community posts, user deletion, shopping integrations.</span></article><article><b>Needs mobile</b><span>Native camera/photo upload, push notifications, TestFlight, App Store assets, privacy labels.</span></article></div></section>
  `)}
})();
